default: &DEFAULT

  # Sent in emails to users
  application_name: 'Folksemantic'
  from_email: 'support@folksemantic.com'
  support_email: 'support@folksemantic.com'
  admin_email: 'admin@folksemantic.com'
  customer_service_number: '1-800-'

  # Email charset
  mail_charset: 'utf-8'

  automatically_activate: true
  automatically_login_after_account_create: true
  send_welcome: true
    
  # if you use recaptcha you will need to also provide a public and private
  # key available from http://recaptcha.net.
  use_recaptcha: false
  recaptcha_pub_key: GET_A_RECAPTCHA_KEY(TODO)
  recaptcha_priv_key: GET_A_RECAPTCHA_KEY(TODO)
  
  # jgrowl related settings
  growl_enabled: false
  
  # application configuration
  let_users_delete_their_account: false  # turn on/off ability for users to delete their own account
  
  # activity configuration
  enable_live_activity_updates: true # Turns on polling inside the user's activity feed so they constantly get updates from the site
  live_activity_update_interval: 60 # time between updates to live activity feed in seconds
  enable_activity_comments: true
  
  #theme configuration
  use_domain_for_themes: true

production:
  <<: *DEFAULT

  # Sent in emails to users
  application_url: 'www.folksemantic.com'

staging:
  <<: *DEFAULT

  # Sent in emails to users
  application_url: 'staging.folksemantic.com'
    
development:
  <<: *DEFAULT

  application_url: 'localhost:3000'
  
test:
  <<: *DEFAULT

  # controls account activation and automatic login
  automatically_activate: false
  automatically_login_after_account_create: false
  
  # turn off for testing
  use_recaptcha: false
  
  application_url: 'localhost:3000'
